# Generated by Django 4.2.5 on 2023-10-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteams',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
